before_script:
- pip install -U flake8 pytest pytest-cov


lint:python2:
  image: 'python:2.7'
  script:
  - flake8

test:python2:
  image: 'python:2.7'
  script:
  - PYTHONPATH=./plugin pytest


lint:python3:
  image: 'python:3.6'
  script:
  - flake8

test:python3:
  image: 'python:3.6'
  coverage: '/^TOTAL +\d+ +\d+ +(\d+%)$/'
  script:
  - PYTHONPATH=./plugin pytest --cov=plugin/

