before_script:
- pip install -U flake8 pytest pytest-cov


test:python2:
  image: 'python:2.7'
  script:
  - flake8
  - pytest


test:python3:
  image: 'python:3.6'
  coverage: '/^TOTAL +\d+ +\d+ +(\d+%)$/'
  script:
  - flake8
  - pytest --cov=plugin/

